PATH=$HOME/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
EDITOR=nvim
BROWSER=firefox
TERMINAL=alacritty
GTK_THEME=Equilux-compact
QT_QPA_PLATFORMTHEME=gtk3
POWERLINE_COMMAND=$HOME/.local/bin/powerline
POWERLINE_CONFIG_COMMAND=$HOME/.local/bin/powerline-config
