# Same image as bspwm: feh --bg-fill on set-wallpaper (blade_runner.jpg)
splash = false

wallpaper {
    monitor = DP-1
    path = /home/hilln/.config/bspwm/wallpaper/2022-Cyberpunk/blade_runner.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/hilln/.config/bspwm/wallpaper/2022-Cyberpunk/blade_runner.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/hilln/.config/bspwm/wallpaper/2022-Cyberpunk/blade_runner.jpg
    fit_mode = cover
}

wallpaper {
    monitor = *
    path = /home/hilln/.config/bspwm/wallpaper/2022-Cyberpunk/blade_runner.jpg
    fit_mode = cover
}
