-- Generated by Profile Loader on 2026-07-13 at 11:00:55. Do not edit manually.

hl.monitor({
    output = "DP-2",
    disabled = true
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@144.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
