-- Generated by Profile Loader on 2026-07-11 at 18:13:39. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@165.0",
    position = "3676x560",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@144.0",
    position = "1116x560",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144.0",
    position = "6236x0",
    scale = 1.0,
    transform = 3
})
