windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = float-qpwgraph
    match:class = ^(qpwgraph)$
    float = true
}

windowrule {
    name = float-misc
    match:class = ^(jack_mixer|Peek|vlc|mplayer|feh|Onboard|Gladish|net-minecraft-bootstrap-Bootstrap)$
    float = true
}
