-- Generated by nwg-displays on 2026-06-17 at 22:14:48. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1"
})
