#!/bin/bash
source $(dirname $0)/config

while true; do
    cputemp=$((`sensors | grep "CPU Temperature" | cut -d'+' -f2 | head -c2`))

    output="%{F$COLOR_ICON} CPU:%{F-}$cputemp°"

    echo $output > /tmp/temp_sensors

    sleep 15
done

