#! /bin/sh
#
# Panel for bspwm using lemonbar
##

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding 14

./panel_data > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
	| lemonbar \
		-f "$FONT1","$FONT2"\
		-F "$COLOR_FOREGROUND"\
		-B "$COLOR_BACKGROUND"\
		-g "$PANEL_GEOMETRY"\
		-u $LINEHEIGHT &
wait

