#! /bin/sh

bspc config border_width        2
bspc config window_gap         	8

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config paddingless_monocole false
bspc config click_to_focus      true
remove_disabled_monitors        true
remove_unplugged_monitors       true

bspc monitor DP-3 -d 1 2 3
bspc monitor DP-1 -d 4 5 6 7
bspc monitor DP-5 -d 8 9 0

# Macbook
bspc monitor eDP1 -d 1 2 3 4 5 6
bspc monitor DP2 -d 7 8 9 0

bspc rule -a Gimp follow=on state=floating
bspc rule -a mplayer state=floating
bspc rule -a vlc state=floating
bspc rule -a feh state=floating
bspc rule -a net-minecraft-bootstrap-Bootstrap state=floating
bspc rule -a steam state=tiled
bspc rule -a peek state=floating

# Compositing
if ! pgrep compton
then
    compton -b
fi

WALLPAPER=$HOME/.config/bspwm/wallpaper
feh --bg-max --no-xinerama $(find $WALLPAPER |shuf -n1)

xsetroot -cursor_name left_ptr

# panel
$HOME/.config/polybar/launch.sh

# autorun
sleep 5s

for exec in dropbox owncloud; do
    pgrep -x $exec
    if [ $? == 1 ]; then
        $exec &
    fi
done

