#! /bin/sh

bspc config border_width        2
bspc config window_gap         	8

bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config paddingless_monocole false
bspc config click_to_focus      true
remove_disabled_monitors        true
remove_unplugged_monitors       true

bspc monitor DP-3 -d I II
bspc monitor DP-1 -d III IV V
bspc monitor DP-5 -d VI VII

# Macbook
bspc monitor DP2 -d I II III IV
bspc monitor eDP1 -d V VI VII

bspc rule -a Gimp follow=on state=floating
bspc rule -a mplayer state=floating
bspc rule -a vlc state=floating
bspc rule -a feh state=floating
bspc rule -a net-minecraft-bootstrap-Bootstrap state=floating
bspc rule -a steam state=tiled

# Compositing
compton -b

WALLPAPER=$HOME/.config/bspwm/wallpaper
feh --bg-max --no-xinerama $(find $WALLPAPER |shuf -n1)

xsetroot -cursor_name left_ptr

