#! /bin/sh

bspc config border_width        1
bspc config window_gap         	8

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DP-1 -d I II III 
bspc monitor DP-3 -d IV V
bspc monitor DP-5 -d VI VII

# Macbook
if [ $(bspc query -M |grep DP2) ]; then
  bspc monitor DP2 -d I II III IV
  bspc monitor eDP1 -d VI VI VII
else
  bspc monitor eDP1 -d I II III IV V VI
fi

bspc rule -a Gimp follow=on floating=on
bspc rule -a Steam follow=off floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a vlc floating=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on
bspc rule -a 'Kerbal Space Program' fullscreen=on

# Panel
#$HOME/.config/bspwm/panel/panel &

# Compositing
compton -b

WALLPAPER=$HOME/.config/bspwm/wallpaper
feh --bg-max --no-xinerama $(find $WALLPAPER |shuf -n1)

